on:
  release:
    types: [created]

jobs:
  release:
    name: release
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: cargo build --release
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/tesseract-console
